### ISSUE TITLE
More detailed error message from /fill-out-form endpoint?

### ISSUE THREAD

**Issue by mikemorris** [EFForg/phantom-of-the-capitol#108]
Looking specifically at https://github.com/EFForg/phantom-of-the-capitol/blob/8fd74b2586ff97a403767e6d952f6a73106ce935/app/helpers/form_fill_handler.rb#L63, would it be possible to pass back the actual error from the remote form, or is this something that could instead be checked in `GET /recent-statuses-detailed/<bio_id>` with a debug key?

**Comment by j-ro** [comment]
Yeah, recent-statuses-detailed has this.
