### ISSUE TITLE
Can't Connect to MySQL Using Docker

### ISSUE THREAD

**Issue by asithade** [EFForg/phantom-of-the-capitol#114]
Been trying to figure out what's going on but when I try to setup the site using `sudo docker-compose up --build` it goes through fine all the way until here: 

```
app_1  | #<Mysql2::Error: Can't connect to MySQL server on '127.0.0.1' (111)>
app_1  | Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "database"=>"phantom_dc", "username"=>"xxx", "password"=>"xxx", "host"=>"127.0.0.1", "pool"=>100, "port"=>"3306"}, charset: utf8, collation: utf8_unicode_ci
```

I've tested the username and password and it connects to MySQL fine. Prior to that, the db_1 looks like it was able to connect to MySQL too. 

```
db_1   | 2017-06-14T23:05:08.365715Z 0 [Note] mysqld: ready for connections.
db_1   | Version: '5.7.18'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
```

Is there something I'm missing here?

**Comment by wioux** [comment]
Make sure this environment variable is set in the app container: `MYSQL_HOST=db`. It's recommended to start development by creating a `.env` file with the initial values in `.env.example`.

**Comment by mr-sk** [comment]
Hello, 

My .env has `MYSQL_HOST=db` in my .env and when I run `sudo docker-compose up --build` I get: 

`db_1   | 2017-06-21T14:27:52.538551Z 4 [Note] Aborted connection 4 to db: 'phantom_dc_development' user: 'phantom_dc' host: '172.18.0.3' (Got an error reading communication packets)`

So, also having the same error.

**Comment by wioux** [comment]
Hi @mr-sk. This is a separate thing, as in your case the app has connected to the db instance but then that connection breaks, while @asithade's app container is not connecting to the db server at all. If you're having problems can you open a separate issue? Be sure to include the app container's output as well around the time of the error.

Thanks,
Peter

**Comment by asithade** [comment]
Hi there, 

I actually get the same error as him when I set it to db.

**Comment by wioux** [comment]
That line will pop up occasionally during a normal boot of the app. Closing this issue for now, but please open another one if you have other problems.
