### ISSUE TITLE
ReCaptcha support

### ISSUE THREAD

**Issue by nilsjesper** [EFForg/phantom-of-the-capitol#118]
It seems like the existing mechanism for completing Captchas is not compatible with ReCaptcha which is increasingly present on various congress forms.

See for example [this screenshot](https://cl.ly/1v3S0j3M3l3u) of bio guide ID A000370.

At this stage, does that mean that the CWC API is the only way forward for contacting these targets?

**Comment by j-ro** [comment]
CWC for the house is vastly preferred, yes. For other options, email me, jason@actionnetwork.org

**Comment by nilsjesper** [comment]
Thanks Jason - will do some additional testing around CWC (once we get our whitelisting set up with them!).  Worth adding a note in the README on this topic?

**Comment by j-ro** [comment]
Email me if you want.
