### ISSUE TITLE
sending html within $MESSAGE

### ISSUE THREAD

**Issue by yocheved** [EFForg/phantom-of-the-capitol#120]
Some forms were failing because of html in the $MESSAGE field.
Should I be able to send html? How do they receive it? Do they see the tags or do they see the tags rendered?
How about a "\n"? Will they see or will they see a newline?
Thank You

**Comment by j-ro** [comment]
Newline is fine, HTML is not. You should clean your messages before you post them. You're filling out a textarea, basically.
