### ISSUE TITLE
If "verify email" is a field, API required fields returns two fields called "$EMAIL". Impossible to reply with two $EMAIL key values.

### ISSUE THREAD

**Issue by Boingoloid** [EFForg/phantom-of-the-capitol#123]
When using the api, for some congresspeople who have both an "email" field and "verify email" field, the required fields returned from the endpoint has two with the same name of "$EMAIL".

I cannot create an object with two keys of the same name and return it.  I'm getting an error if I just return 1 $EMAIL value.  Anyone know how to work around this?  Thanks

One example.  Richard C. Shelby . Sen AL.  bioguideID "S000320"

**Comment by j-ro** [comment]
I think we just return one, and it works fine.

**Comment by Boingoloid** [comment]
Thank you for replying.  I really appreciate it.  I'm still getting an error.  Here is the dictionary I'm sending.  Works for other congresspeople fine, but not for bioguide S000320.  If you have time, would you mind taking a look below and see if you can spot an error?

Thank in advance.

{"bio_id":"S000320","campaign_tag":"push_thought","fields":{"$SUBJECT":"test email","$NAME_PREFIX":"Dr.","$NAME_FIRST":"matt","$NAME_LAST":"matt","$EMAIL":"matt.matt@gmail.com","$PHONE":"6177841234","$ADDRESS_STREET":"260 king","$ADDRESS_CITY":"Birmingham","$ADDRESS_ZIP5":"35006","$TOPIC":"ARTS","$MESSAGE":"Congressperson Richard C. Shelby,\n\nthis is a test email.\n"}}

**Comment by j-ro** [comment]
Shelby has recaptcha on his form, so you're going to have to do some special stuff for that to get a success.

**Comment by Boingoloid** [comment]
I'm getting a status of . error message, email submit:An error has occurred while filling out the remote form.

Instead of {"status":"captcha_needed","url":"/captchas/e410e577123c5e19a526ad3f6b.png"}

**Comment by j-ro** [comment]
Recaptcha and captcha are quite different. Email me if you'd like to discuss more.
