### ISSUE TITLE
add this project to ios mobile project

### ISSUE THREAD

**Issue by ahspadafora** [EFForg/phantom-of-the-capitol#128]
Hey there
I would like to use your api in a mobile app I am building (in swift)

Could you point me in the right direction for implementing this? I am only really familiar with iOS development

**Comment by j-ro** [comment]
Hello! I think the way you'd work with this is you'd run this project on a remote server in the cloud, and have your iOS app connect to the HTTP/JSON API that the server would expose. I don't think you could run this project on a mobile device itself exactly.

**Comment by ahspadafora** [comment]
Awesome! I really appreciate you breaking it down in laymen terms because I am entering unknown territory and your explanation gives me a great starting point.

**Comment by j-ro** [comment]
Great, best of luck!

**Comment by ahspadafora** [comment]
@j-ro do you know of anyone who is already running this and has a public api?

**Comment by j-ro** [comment]
There are no public APIs of this project that I know of.

**Comment by ahspadafora** [comment]
would I be able to run this on heroku?

**Comment by j-ro** [comment]
I expect so, but I'm not a Heroku expert.
