### ISSUE TITLE
How are you solving reCAPTCHA?

### ISSUE THREAD

**Issue by Jefftopia** [EFForg/phantom-of-the-capitol#146]
Hi all, I'm curious if you could explain how you're solving (or not solving) reCAPTCHA? I'm trying to roll my own solution using puppeteer. What I have is basic; I was hoping I could just send the iframe url to the user but there's an DOM event error when the url isn't the same as the whitelisted host url.

**Comment by j-ro** [comment]
Feel free to follow up with me offline, seminal@theseminal.com
