### ISSUE TITLE
Lots of "Request failed to reach server, check DNS and/or server status" errors

### ISSUE THREAD

**Issue by Hainish** [EFForg/phantom-of-the-capitol#47]
I've been getting a lot of these:

<pre>
############################################
Message:
Request failed to reach server, check DNS and/or server status
e:
#<Capybara::Poltergeist::StatusFailError: ---
:message: Request failed to reach server, check DNS and/or server status
:screenshot: https://congress-forms.s3.amazonaws.com/production/screenshots/2626df029f476f6c86035b1c61.png
>
backtrace:
/home/legind/workspace/congress-forms/app/models/congress_member.rb:282:in `rescue in fill_out_form_with_capybara'
/home/legind/workspace/congress-forms/app/models/congress_member.rb:301:in `fill_out_form_with_capybara'
/home/legind/workspace/congress-forms/app/models/congress_member.rb:175:in `fill_out_form_with_poltergeist'
/home/legind/workspace/congress-forms/app/models/congress_member.rb:45:in `fill_out_form'
tasks/congress-forms.rake:48:in `block (4 levels) in <top (required)>'
tasks/congress-forms.rake:43:in `each'
tasks/congress-forms.rake:43:in `block (3 levels) in <top (required)>'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/legind/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/bin/rake:23:in `load'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/bin/rake:23:in `<main>'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/bin/ruby_executable_hooks:15:in `eval'
/home/legind/.rvm/gems/ruby-2.1.0@congress-forms/bin/ruby_executable_hooks:15:in `<main>'
############################################
</pre>

This has to do with https://github.com/ariya/phantomjs/issues/12234 and https://github.com/teampoltergeist/poltergeist/issues/375

**Comment by NullVoxPopuli** [comment]
does this happen when you call `visit`? that's my problem

**Comment by Hainish** [comment]
Yes, on `visit`.  It's pretty sporadic.

**Comment by PrakashChoudhary-20** [comment]
I am facing the same issue. Did you find any solution to it?

**Comment by PrakashChoudhary-20** [comment]
Tried connecting to the 'HTTP' requests and it worked fine for me. However, working with 'HTTPS' is causing this problem.

**Comment by juhlila** [comment]
did anyone find a solution for this? its also occurring to me

**Comment by j-ro** [comment]
Only dropping by to say we generally don't see this at all, not sure why.

**Comment by Hainish** [comment]
This is occurring less now than it did before, after upgrading the instance of AWS we're running.  @NullVoxPopuli, @PrakashChoudhary-20, are you encountering this error on resource-confined machines?

**Comment by NullVoxPopuli** [comment]
my issue was actually that my travis config was configured for wrong url - so the error was totally warranted.

**Comment by chamnap** [comment]
I faced the same problem. Try this domain, https://bitsapphire.com/, you will see this error.

**Comment by Hainish** [comment]
This seems to be pretty much occurring not at all anymore.  May have been resolved as of the newest phantomjs release, closing

**Comment by juanibiapina** [comment]
@Hainish what release are you talking about at this point?

**Comment by Hainish** [comment]
We're up to 2.1.1. Phantom DC has updated to support that release.
