### ISSUE TITLE
Click not working?

### ISSUE THREAD

**Issue by crdunwel** [EFForg/phantom-of-the-capitol#67]
https://github.com/EFForg/phantom-of-the-capitol/blob/master/app/models/congress_member.rb#L245

May consider doing something like

```
ele = session.find(a.selector)
if ele.tag_name == 'input' or ele.tag_name == 'button'
  ele.trigger('click')
else
  ele.click
end
```

This is suggested for poltergeist README as a workaround. - https://github.com/teampoltergeist/poltergeist#mouseeventfailed-errors

It's late so I'll try to see if I can test this more tomorrow. Messages seem to be going through, but I'm getting two screenshots, one right before submission and one with the success page. But yet I'm getting a failure message. So may be my phantom-of-the-capitol is messed up somehow. If somebody else can test this out that'd be great. The problem cases that this is trying to address are the new-style forms such as https://github.com/unitedstates/contact-congress/blob/master/members/B001293.yaml .

**Comment by Hainish** [comment]
closing, I'll reopen if I start encountering this issue more
