### ISSUE TITLE
Make data sources flexible

### ISSUE THREAD

**Issue by Hainish** [EFForg/phantom-of-the-capitol#68]
It would be nice if we were able to add and delete data sources via a CLI.  Currently, this project has one data source, hard coded to https://github.com/unitedstates/contact-congress.  Because of this tight coupling, @j-ro has has forked the repo to add other data sources such as state congresses.  This is not ideal, we should maintain one codebase and add / remove data sources on a per-instance basis.

All data sources should maintain the formatting of the `contact-congress` repo:
- Have a git url
- Have a subfolder with YAML files
- YAML instruction set should mirror the `contact-congress` instruction set

This is in progress currently, and after this feature is built in anyone can choose any arbitrary data sources they like.  When pulled in to the local database, bioguide ids can be prefixed by data source.  For instance, if it's the California state senate, prefixing with `CA_` seems prudent.

Comments, @j-ro?

**Comment by j-ro** [comment]
On my roadmap for the coming year (starting in July) is updates to our phantom implementation, and one of them is this and committing it back, plus grabbing the current code so we're all running one version again. I'm not sure exactly how we do it right now, though I don't do the bioguide ID prefixing (I'm just making up new ones for state level).

My state level data is here: https://github.com/j-ro/contact-states
And some other data we use is here, like the bioguide ID list: https://github.com/j-ro/congress-forms-data

So, I'm happy to take this one, as this was our plan anyway. Not sure exactly when that'll happen this coming year, but it's in the plan.

**Comment by Hainish** [comment]
:+1:

**Comment by Hainish** [comment]
Has been implemented as of https://github.com/EFForg/phantom-of-the-capitol/commit/b69c9523889f78b4b68c947b2c59d44f19269124
