### ISSUE TITLE
Javascript Alerts

### ISSUE THREAD

**Issue by jscanzoni** [EFForg/phantom-of-the-capitol#73]
Is there a way to read the contents of javascript alert boxes?

My thought is that it either requires using a different driver which allows window switching, or I'll have to inject javascript into the page to override the javascript alert function altogether. Is there something already in phantom-of-the-capitol which allows me to read the text from alert windows?

Specifically, I am trying to tackle this form: http://www.senate.leg.state.mn.us/members/member_emailform.php?mem_id=1010 ... Until I can read the javascript alert text, I'll keep getting false negatives.

**Comment by j-ro** [comment]
We've not tried to implement this, but right now there is no way to read the contents, no.
