### ISSUE TITLE
$MESSAGE not always in required_actions

### ISSUE THREAD

**Issue by rubbingalcoholic** [EFForg/phantom-of-the-capitol#75]
Some Congress forms, such as [Ayotte](https://github.com/unitedstates/contact-congress/blob/master/members/A000368.yaml) can be submitted without actually entering a $MESSAGE (not a required field)

So the `retrieve-form-elements` endpoint doesn't always list this field in the `required_actions` hash. If the client only fills fields based on the `required_actions`, and the Congress form doesn't require the field, it's possible to submit forms with no message.

A workaround is to always force the client to submit a $MESSAGE, even when it's not in `required_actions`. But is it considered a problem with phantom-dc that $MESSAGE isn't always assumed to be required? Maybe not, but thought I'd raise the question.

**Comment by j-ro** [comment]
I don't think this is a phatom-of-the-capitol issue, no. Generally, in the YAML, we'll mark the message as required even if it's technically not, because the point of filling the form is to submit a message, but I think it's appropriate to handle that in-yaml.

**Comment by Hainish** [comment]
I agree with @j-ro here.  Interesting question, though!  Closing now.
