### ISSUE TITLE
403 Forbidden response codes from certain web forms

### ISSUE THREAD

**Issue by tech-workwithiws** [EFForg/phantom-of-the-capitol#80]
We are getting a 403 "Access Denied" message from a high percentage of the congressional webforms, primarily Senators.

The full message is:

"you don't have permissions to access 'http://serve-403-everyone.www.senate.gov/contact'" on this server"

I'm assuming that our IP has been flagged, since CURL calls to specific webforms from the server running Phantom return the 403 response, whereas the same call from other servers resolves just fine.

Has anyone encountered this or know what sort of activity may have caused our IP to be blocked?  Besides switching servers, are their other options for circumventing this issue?

Thanks

**Comment by j-ro** [comment]
We did yesterday too, so must have been a mass blocking. We solved it by switching IPs. No blocks yet.

I'm trying to get in touch with people in the Senate who manage stuff like this through contacts, so I may have more info on what triggered the block and how to avoid it in the future soon. But for now, switch IPs.

**Comment by tech-workwithiws** [comment]
Great, thanks.  I will give that a try. 

I'd be interested to hear if you're able to make any progress with your Senate contacts.  I'm sure it's just a matter of time before our new IPs are flagged, so figuring out how to avoid this in the future would be great.

**Comment by j-ro** [comment]
yeah, we were blocked again today it seems. I'll let you know if we make progress.

**Comment by tech-workwithiws** [comment]
Looks like we've been blocked again now, too.  It seems like they are monitoring pretty closely and continuing to switch IPs is probably no longer a viable option.

Were you able to get anywhere with your contacts in the Senate?

Thanks

**Comment by j-ro** [comment]
Yes, I think so, but slowly. I'll let you know when I have more.

**Comment by tech-workwithiws** [comment]
Great, thanks for your work on this.

**Comment by j-ro** [comment]
Alright, we've gotten ourselves unblocked. It's a firewall thing, so the IP address we use for phantom has now been whitelisted. 

Unfortunately, there's not a quick or easy solution for others. Basically, you need to go through a Senate office. I asked a friend that works in one. They'll need to get in touch with the Sargent At Arms (SAA), who handles IT infrastructure, and the office will need to vouch for you. Potentially SAA may have more questions, but that's essentially what we did, and what I was recommended to tell others to do.

I'll mark this as closed for now, I suppose.

**Comment by tech-workwithiws** [comment]
Great.  Thanks Jason.  We will give this a try.
