### ISSUE TITLE
Debugging endpoint jobs are loading slowly

### ISSUE THREAD

**Issue by TheNotary** [EFForg/phantom-of-the-capitol#88]
Offending URL (minus key):
  https://efforg.github.io/congress-forms-test/?bioguide_id=A000055&debug_key=

When you first load the page, the jobs pane loads slowly.  

This is due to having to deserialize every job, then check whether it's pertinent for the current MoC.  We should use a join table for this purpose instead (possibly FillStatus)

**Comment by j-ro** [comment]
I'm unsure if this site is still meant to be really live or working. We certainly haven't used it in a while.

**Comment by TheNotary** [comment]
I'm new, is there an alternative way to debug, re-attempt form post submissions for failed attempts on member's of congress' websites?

**Comment by j-ro** [comment]
Typically, we do this with our own debug endpoints in our own installation (so yours would be different from ours) and re-run via command line.

**Comment by j-ro** [comment]
btw, if you want more details on our setup, email is better than the public forum, in my profile

**Comment by Hainish** [comment]
Debugging endpoints are loading *much* quicker now, since adding a FillStatus <-> Delayed::Job join table.  This helps with the 'list-jobs' debug route.  If there are lots of previous fills, the 'recent-fill-statuses' route is still a bit slow, since it has to return lots of results in the body.
