### ISSUE TITLE
Recaptcha handling planning

### ISSUE THREAD

**Issue by j-ro** [EFForg/phantom-of-the-capitol#93]
Re: #90, want to start a planning issue here, then break out into real issues once we're clear on what needs to be done.

# Overview

Google's Recaptcha continues to be updated with new security features, meaning a never-ending treadmill of updates to phantom if we want it to continue to work.

For now, given that not too many members of congress use Recaptcha, the best solution seems to be submitting these form fills manually using Watir on an instance of phantom being run locally, and creating some tooling and infrastructure to allow that to happen efficiently.

# Pieces

The pieces to make this happen as I understand:

### Config Variable & Special Handling for Recaptcha YAML instructions

We'll need a config variable that can be set when running phantom to indicate we'd like to run YAMLs that contain Recaptcha through Watir, as well as removing `Headless.start` from `boot.rb` as mentioned in #90.  This should be separate from the `REQIRES_WATIR` config variable, which specifies that YAML files with specified bioguides should *always* be run through Watir. We already have an instruction to indicate if a certain YAML file has a recaptcha element. If the above variable is set, we'll want to make phantom run those YAMLs using Watir when they're encountered.

### Rake task for running recaptchas

We'll want a rake task that looks for all outstanding, non-successfully filled form fills on YAMLs that have the recaptcha element and then runs through them one by one, so the user running phantom locally can go through all of them in one session, quickly and easily, clicking on the captcha to verify human-ness and completing the form fill.

@Hainish, did I get that about right? @gcosta FYI, this is where we're going to be headed once we're done with our current issues and move on...

**Comment by j-ro** [comment]
@Hainish when you can, let me know if I've got all this right. Ideally we'd be able to get started on this work next week.

**Comment by Hainish** [comment]
@j-ro I've updated the comment under "pieces" to combine the first 2 pieces and change the wording a bit.  otherwise looks good

**Comment by j-ro** [comment]
Great, I updated too with your note from #90 about the boot script.  I may have not got that exactly right but I think the meaning is clear enough -- when you run in the recaptcha mode you should also run non-headless.

**Comment by Hainish** [comment]
yup!
