### ISSUE TITLE
Support test posts to /fill-out-form

### ISSUE THREAD

**Issue by wioux** [EFForg/phantom-of-the-capitol#99]
Based on a URL param like `testmode=1`? This would be useful to client applications that integrate with phantom-dc (for their staging environments, testing, development, etc.) so that you can fully exercise the form and integration without actually messaging congress.

In test mode the endpoint should fail if mandatory fields are omitted or the bio_id is invalid, but otherwise return `{status: "success"}` without actually running the form steps.

**Comment by j-ro** [comment]
We implement test mode on the app side, that's our solution for this. But feel free to add if you'd like!
